artifact_uri: file:///home/samuel/Documents/MARLClassification/mlruns/1/6c13dc4f2b764a01a3f9f9e4e6f8ca9f/artifacts
end_time: 1605166927821
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 6c13dc4f2b764a01a3f9f9e4e6f8ca9f
run_uuid: 6c13dc4f2b764a01a3f9f9e4e6f8ca9f
source_name: ''
source_type: 4
source_version: ''
start_time: 1605127169768
status: 3
tags: []
user_id: samuel
