repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
        files: "./marl_classification/*"
    -   id: trailing-whitespace
        files: "./marl_classification/*"
- repo: local
  hooks:
    - id: mypy
      name: mypy
      language: system
      entry: mypy
      types:
        - python