[tool.black]
line-length = 79

[tool.pycln]
all = true

[tool.isort]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
ignore_missing_imports = true
warn_return_any = true
disallow_untyped_defs = true

[tool.pylint]
good-names-rgxs = "^[_a-z][_a-z0-9]?$"
max-line-length = 100
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "too-many-instance-attributes",
    "too-many-arguments",
    "too-many-locals",
    "too-few-public-methods",
    "too-many-statements",
    "no-member",
    "import-error"
]
