[tool.pycln]
all = true

[tool.isort]
line_length = 80
multi_line_output = 3
include_trailing_comma = false
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = false

[tool.mypy]
ignore_missing_imports = true
