# Ipsedo's Python continuous integration

name: Python continuous integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  python_ci:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python 3.14
      uses: actions/setup-python@v7
      with:
        python-version: "3.14"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        python -m uv sync
    - name: Check code
      run: |
        python -m uv run mypy marl_classification tests
        python -m uv run pylint marl_classification tests
    - name: Test code
      run: |
        python -m uv run pytest tests
